### ISSUE TITLE
Cope with broken web clients

### ISSUE THREAD

**Issue by palfrey** [palfrey/kitling#12]
Sometimes the internal mutex gets horribly broken, and that needs fixing

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore/result.rs:746
stack backtrace:
   1:     0x7ff4676738c0 - std::sys::backtrace::tracing::imp::write::h4c73fcd3363076f5
   2:     0x7ff4676784cb - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0422dbb3077e6747
   3:     0x7ff467678153 - std::panicking::default_hook::haac48fa641db8fa2
   4:     0x7ff46766474f - std::sys_common::unwind::begin_unwind_inner::h39d40f52add53ef7
   5:     0x7ff467665f78 - std::sys_common::unwind::begin_unwind_fmt::h64c0ff793199cc1b
   6:     0x7ff467672b11 - rust_begin_unwind
   7:     0x7ff4676ae66f - core::panicking::panic_fmt::h73bf9d7e8e891a73
   8:     0x7ff46708ed39 - core::result::unwrap_failed::h6c8199caa816074c
                        at ../src/libcore/macros.rs:29
   9:     0x7ff46708e979 - _<core..result..Result<T, E>>::unwrap::he8f0f16950e32eaa
                        at ../src/libcore/result.rs:687
  10:     0x7ff46708e86c - _<nickel..Request<'a, 'b, D> as chromedriver..WebdriverRequestExtensions>::webdriver::ha6f324d6e20daeb4
                        at src/chromedriver.rs:207
  11:     0x7ff46707ffd8 - kitling_imager::streams::h8e67ee5e45503d51
                        at src/main.rs:140
  12:     0x7ff467166b22 - fn(&mut nickel..Request<'_, '_>, nickel..Response<'_>) .> core..result..Result<nickel..Action<nickel..Response<'_>, nickel..Response<'_, (), hyper..net..Streaming>>, nickel..NickelError<'_>> $u7b$streams..$LT$$LP$$RP$$GT$$u7d$::fn_pointer_shim.22235::hc7897858f91d9912
  13:     0x7ff46707f2b5 - _<T as nickel..Middleware<D>>::invoke::h08b72096852c3597
                        at /root/.cargo/registry/src/github.com-88ac128001ac3a9a/nickel-0.8.1/src/middleware.rs:27
  14:     0x7ff467167f92 - _<nickel..Router<D> as nickel..Middleware<D>>::invoke::h90d742e0efcc7643
                        at /root/.cargo/registry/src/github.com-88ac128001ac3a9a/nickel-0.8.1/src/router/router.rs:114
  15:     0x7ff46717f671 - _<nickel..middleware..MiddlewareStack<D>>::invoke::hd542798cc1b893a4
                        at /root/.cargo/registry/src/github.com-88ac128001ac3a9a/nickel-0.8.1/src/middleware.rs:57
  16:     0x7ff46717f04b - _<nickel..server..ArcServer<D> as hyper..server..Handler>::handle::h4e3dc4209a1d6950
                        at /root/.cargo/registry/src/github.com-88ac128001ac3a9a/nickel-0.8.1/src/server.rs:31
  17:     0x7ff4671780ab - _<hyper..server..Worker<H>>::keep_alive_loop::h200b81f5d5fc7475
                        at /root/.cargo/registry/src/github.com-88ac128001ac3a9a/hyper-0.8.1/src/server/mod.rs:356
  18:     0x7ff4671749ce - _<hyper..server..Worker<H>>::handle_connection::h6196d3650726c43e
                        at /root/.cargo/registry/src/github.com-88ac128001ac3a9a/hyper-0.8.1/src/server/mod.rs:293
  19:     0x7ff467173c97 - hyper::server::handle::_$u7b$$u7b$closure$u7d$$u7d$::he7be59856c4b9d10
  20:     0x7ff46718b579 - hyper::server::listener::spawn_with::_$u7b$$u7b$closure$u7d$$u7d$::hdf37a26a8cfb6ab9
  21:     0x7ff46718aecd - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h6be3116d37c0ea9d
  22:     0x7ff46718ae69 - std::sys_common::unwind::try::try_fn::hd4a9dd98f1a0340e
                        at ../src/libstd/sys/common/unwind/mod.rs:127
  23:     0x7ff467672a9b - __rust_try
  24:     0x7ff467672a2d - std::sys_common::unwind::inner_try::h9eebd8dc83f388a6
  25:     0x7ff46718add2 - std::sys_common::unwind::try::h568b44b7f21d6b96
                        at ../src/libstd/sys/common/unwind/mod.rs:123
  26:     0x7ff46718ac36 - std::thread::Builder::spawn::_$u7b$$u7b$closure$u7d$$u7d$::hc791917054669cfc
  27:     0x7ff46718b9f8 - _<F as std..boxed..FnBox<A>>::call_box::h879a393d2abd153f
                        at ../src/liballoc/boxed.rs:541
  28:     0x7ff467676c44 - std::sys::thread::Thread::new::thread_start::h471ad90789353b5b
  29:     0x7ff465c2c0a3 - start_thread
  30:     0x7ff466a8a87c - clone
  31:                0x0 - <unknown>
```

**Comment by palfrey** [comment]
https://crates.io/crates/antidote might help here
